const bcrypt = require('bcryptjs');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    try {
      const adminPassword = await bcrypt.hash('admin123', 10);
      const asesorPassword = await bcrypt.hash('asesor123', 10);
      
      return queryInterface.bulkInsert('Users', [
        {
          username: 'admin',
          password: adminPassword,
          role: 'admin',
          nombres: 'Ana María',
          apellidos: 'Rodríguez',
          correo: 'ana.rodriguez@creditpro.com',
          telefono: '3001234567',
          theme: 'light',
          estado: 'activo',
          sucursal: 'Principal',
          // Permisos de administrador - todos en true
          creditos_ver: true,
          creditos_crear: true,
          creditos_editar: true,
          creditos_eliminar: true,
          clientes_ver: true,
          clientes_crear: true,
          clientes_editar: true,
          clientes_eliminar: true,
          asesores_ver: true,
          asesores_crear: true,
          asesores_editar: true,
          asesores_eliminar: true,
          bancos_ver: true,
          bancos_crear: true,
          bancos_editar: true,
          bancos_eliminar: true,
          financieras_ver: true,
          financieras_crear: true,
          financieras_editar: true,
          financieras_eliminar: true,
          objetivos_ver: true,
          objetivos_crear: true,
          objetivos_editar: true,
          objetivos_eliminar: true,
          reportes_ver: true,
          reportes_crear: true,
          reportes_editar: true,
          reportes_eliminar: true,
          comisiones_ver: true,
          comisiones_crear: true,
          comisiones_editar: true,
          comisiones_eliminar: true,
          configuracion_ver: true,
          configuracion_crear: true,
          configuracion_editar: true,
          configuracion_eliminar: true,
          gestionUsuarios_ver: true,
          gestionUsuarios_crear: true,
          gestionUsuarios_editar: true,
          gestionUsuarios_eliminar: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: 'carlos.mendoza',
          password: adminPassword,
          role: 'admin',
          nombres: 'Carlos',
          apellidos: 'Mendoza',
          correo: 'carlos.mendoza@creditpro.com',
          telefono: '3007654321',
          theme: 'dark',
          estado: 'activo',
          sucursal: 'Norte',
          // Permisos de administrador - todos en true
          creditos_ver: true,
          creditos_crear: true,
          creditos_editar: true,
          creditos_eliminar: true,
          clientes_ver: true,
          clientes_crear: true,
          clientes_editar: true,
          clientes_eliminar: true,
          asesores_ver: true,
          asesores_crear: true,
          asesores_editar: true,
          asesores_eliminar: true,
          bancos_ver: true,
          bancos_crear: true,
          bancos_editar: true,
          bancos_eliminar: true,
          financieras_ver: true,
          financieras_crear: true,
          financieras_editar: true,
          financieras_eliminar: true,
          objetivos_ver: true,
          objetivos_crear: true,
          objetivos_editar: true,
          objetivos_eliminar: true,
          reportes_ver: true,
          reportes_crear: true,
          reportes_editar: true,
          reportes_eliminar: true,
          comisiones_ver: true,
          comisiones_crear: true,
          comisiones_editar: true,
          comisiones_eliminar: true,
          configuracion_ver: true,
          configuracion_crear: true,
          configuracion_editar: true,
          configuracion_eliminar: true,
          gestionUsuarios_ver: true,
          gestionUsuarios_crear: true,
          gestionUsuarios_editar: true,
          gestionUsuarios_eliminar: true,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: 'laura.martinez',
          password: asesorPassword,
          role: 'user',
          nombres: 'Laura',
          apellidos: 'Martínez',
          correo: 'laura.martinez@creditpro.com',
          telefono: '3009876543',
          theme: 'system',
          estado: 'activo',
          sucursal: 'Sur',
          // Permisos de asesor - limitados
          creditos_ver: true,
          creditos_crear: true,
          creditos_editar: true,
          creditos_eliminar: false,
          clientes_ver: true,
          clientes_crear: true,
          clientes_editar: true,
          clientes_eliminar: false,
          asesores_ver: true,
          asesores_crear: false,
          asesores_editar: false,
          asesores_eliminar: false,
          bancos_ver: true,
          bancos_crear: false,
          bancos_editar: false,
          bancos_eliminar: false,
          financieras_ver: true,
          financieras_crear: false,
          financieras_editar: false,
          financieras_eliminar: false,
          objetivos_ver: true,
          objetivos_crear: false,
          objetivos_editar: false,
          objetivos_eliminar: false,
          reportes_ver: true,
          reportes_crear: false,
          reportes_editar: false,
          reportes_eliminar: false,
          comisiones_ver: true,
          comisiones_crear: false,
          comisiones_editar: false,
          comisiones_eliminar: false,
          configuracion_ver: false,
          configuracion_crear: false,
          configuracion_editar: false,
          configuracion_eliminar: false,
          gestionUsuarios_ver: false,
          gestionUsuarios_crear: false,
          gestionUsuarios_editar: false,
          gestionUsuarios_eliminar: false,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: 'roberto.silva',
          password: asesorPassword,
          role: 'user',
          nombres: 'Roberto',
          apellidos: 'Silva',
          correo: 'roberto.silva@creditpro.com',
          telefono: '3005432167',
          theme: 'light',
          estado: 'inactivo',
          sucursal: 'Centro',
          // Permisos de asesor - limitados
          creditos_ver: true,
          creditos_crear: true,
          creditos_editar: true,
          creditos_eliminar: false,
          clientes_ver: true,
          clientes_crear: true,
          clientes_editar: true,
          clientes_eliminar: false,
          asesores_ver: true,
          asesores_crear: false,
          asesores_editar: false,
          asesores_eliminar: false,
          bancos_ver: true,
          bancos_crear: false,
          bancos_editar: false,
          bancos_eliminar: false,
          financieras_ver: true,
          financieras_crear: false,
          financieras_editar: false,
          financieras_eliminar: false,
          objetivos_ver: true,
          objetivos_crear: false,
          objetivos_editar: false,
          objetivos_eliminar: false,
          reportes_ver: true,
          reportes_crear: false,
          reportes_editar: false,
          reportes_eliminar: false,
          comisiones_ver: true,
          comisiones_crear: false,
          comisiones_editar: false,
          comisiones_eliminar: false,
          configuracion_ver: false,
          configuracion_crear: false,
          configuracion_editar: false,
          configuracion_eliminar: false,
          gestionUsuarios_ver: false,
          gestionUsuarios_crear: false,
          gestionUsuarios_editar: false,
          gestionUsuarios_eliminar: false,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          username: 'patricia.gomez',
          password: asesorPassword,
          role: 'user',
          nombres: 'Patricia',
          apellidos: 'Gómez',
          correo: 'patricia.gomez@creditpro.com',
          telefono: '3002468135',
          theme: 'dark',
          estado: 'activo',
          sucursal: 'Principal',
          // Permisos de asesor - limitados
          creditos_ver: true,
          creditos_crear: true,
          creditos_editar: true,
          creditos_eliminar: false,
          clientes_ver: true,
          clientes_crear: true,
          clientes_editar: true,
          clientes_eliminar: false,
          asesores_ver: true,
          asesores_crear: false,
          asesores_editar: false,
          asesores_eliminar: false,
          bancos_ver: true,
          bancos_crear: false,
          bancos_editar: false,
          bancos_eliminar: false,
          financieras_ver: true,
          financieras_crear: false,
          financieras_editar: false,
          financieras_eliminar: false,
          objetivos_ver: true,
          objetivos_crear: false,
          objetivos_editar: false,
          objetivos_eliminar: false,
          reportes_ver: true,
          reportes_crear: false,
          reportes_editar: false,
          reportes_eliminar: false,
          comisiones_ver: true,
          comisiones_crear: false,
          comisiones_editar: false,
          comisiones_eliminar: false,
          configuracion_ver: false,
          configuracion_crear: false,
          configuracion_editar: false,
          configuracion_eliminar: false,
          gestionUsuarios_ver: false,
          gestionUsuarios_crear: false,
          gestionUsuarios_editar: false,
          gestionUsuarios_eliminar: false,
          createdAt: new Date(),
          updatedAt: new Date()
        }
      ], { ignoreDuplicates: true }); // Evita duplicados si el seeder se ejecuta múltiples veces
    } catch (error) {
      console.error('Error in user seeder:', error);
      throw error;
    }
  },

  down: async (queryInterface, Sequelize) => {
    try {
      return queryInterface.bulkDelete('Users', {
        username: { 
          [Sequelize.Op.in]: [
            'admin', 
            'carlos.mendoza', 
            'laura.martinez',
            'roberto.silva',
            'patricia.gomez'
          ] 
        }
      }, {});
    } catch (error) {
      console.error('Error undoing user seeder:', error);
      throw error;
    }
  }
};